version: '3'

services:

    unbound:
        image: qeynos/unbound-redis-scratch    
        container_name: unbound
        ports:
            - 53:53/udp
        restart: always
        volumes:
            - ./unbound:/etc/unbound

    redis:
        image: redis
        container_name: redis
        restart: always
        volumes:
            - ./redis:/data
        command: redis-server /data/redis.conf
